# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  major: 1
  minor: 2
  GLOBAL_NEXUSKEY: $(NexusKey)

name: $(major).$(minor)$(Rev:.r)

steps:
  - task: CmdLine@2
    inputs:
      script: 'tree ./ /f'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script:  Write-Host (Test-Path ("/home/vsts/work/1/s/mod_root/manifest.json"))
  - task: PowerShell@2
    inputs:
      filePath: './build/build.ps1'
      arguments: '-Version $(Build.BuildNumber) -NexusKey $($ENV:GLOBAL_NEXUSKEY)'
      failOnStderr: true
    env:
      GLOBAL_NEXUSKEY: $(GLOBAL_NEXUSKEY)

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)/s/out'
      artifact: 'output'
      publishLocation: 'pipeline'